import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateArtFromFeelings = async (feelings: string): Promise<string> => {
    try {
        const fullPrompt = `Create a visually stunning, abstract therapeutic art piece that represents the following feeling or situation: "${feelings}". The style should be dreamlike and expressive, using a soft, calming color palette. Focus on textures and symbolic imagery rather than literal representation.`;

        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: fullPrompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image with Gemini API:", error);
        // Re-throw the original error to allow the UI to display a more specific message.
        throw error;
    }
};
